#!/bin/bash
# This script will help you ban any IP in the /24 starting at 2, Just in case your Router is 1
# change the valour after NE to specify what you want to leave unbanned

i=2
while [ $i -le 253 ]
do
        if [ $i -ne 20 -a $i -ne 21 -a $i -ne 22 ]; then
                echo "BANNED: arp -s 192.168.1.$i"
        else
                echo "IP NOT BANNED: 192.168.1.$i***********"
                echo "**************************************"
        fi
        i=`expr $i + 1`
done
